#!/usr/bin/env bash
# HarmonyOS BLE BMS 构建脚本 (Linux 命令行工具链)
# 用法: ./build.sh [hvigor任务]  默认 assembleHap
#
# 工具链位置: $HARMONYOS_TOOLS (默认 ~/harmonyos/command-line-tools)
# 本脚本会自动生成 hvigor/hvigor-config.json5 (file: 依赖指向本地 hvigor, 免下载)。
set -euo pipefail

TOOLS="${HARMONYOS_TOOLS:-$HOME/harmonyos/command-line-tools}"
HVIGOR_CFG="$(dirname "$0")/hvigor/hvigor-config.json5"

export DEVECO_SDK_HOME="$TOOLS/sdk"
export NODE_HOME="$TOOLS/tool/node"
export NODE_PATH="$TOOLS/tool/node/lib/node_modules"
export PATH="$TOOLS/bin:$TOOLS/tool/node/bin:$PATH"
export npm_config_registry="https://repo.huaweicloud.com/repository/npm/"

# 生成 hvigor 配置 (使用 file: 依赖直接使用命令行工具自带的 hvigor, 无需联网下载)
if [[ ! -f "$HVIGOR_CFG" ]] || grep -q '@@TOOLS@@' "$HVIGOR_CFG"; then
  mkdir -p "$(dirname "$HVIGOR_CFG")"
  cat > "$HVIGOR_CFG" <<EOF
// @generated by build.sh — 用 DevEco Studio 打开工程时请改用 hvigor-config.example.json5
{
  "modelVersion": "5.1.0",
  "dependencies": {
    "@ohos/hvigor": "file:$TOOLS/hvigor/hvigor",
    "@ohos/hvigor-ohos-plugin": "file:$TOOLS/hvigor/hvigor-ohos-plugin"
  },
  "execution": {},
  "logging": {},
  "debugging": {},
  "nodeOptions": {}
}
EOF
  echo ">> 已生成 hvigor/hvigor-config.json5 (工具链: $TOOLS)"
fi

cd "$(dirname "$0")"

TASK="${1:-assembleHap}"
if [[ "$TASK" == -* || "$TASK" == assemble* || "$TASK" == clean || "$TASK" == sync || "$TASK" == *Hap* || "$TASK" == *App* ]]; then
  exec "$TOOLS/hvigor/bin/hvigorw" --no-daemon "$TASK" "$@"
else
  exec "$TOOLS/hvigor/bin/hvigorw" --no-daemon "$@"
fi
